#!/bin/bash

# Tutorial:
# 
# Crea un video a partir de imagenes. Requiere de ImageMagick y FFmpeg.
# 
# USO: ./run_movie myfile
#
# Warning: do not include wildcards or extenions!
# Example: ./run_movie geometry
#

args=("$@")

#echo "Number of arguments: $#"
#echo "primero: ${args[0]}"

myfile="${args[0]}_*.eps"

i=0

for file in ${myfile}
do
    mv "${args[0]}_${i}.eps" "output_${i}.eps"
    let i=i+1
done


echo -e "\nConverting ${myfile} to .png...\n"

mogrify -density 300 -format png output_*.eps

rm output_*.eps

#for file in ${myfile}
#do
#    filename=$(basename "$file")
#    filename=${filename%.*}
#    convert -density 300 $file $filename.png
#done

echo -e "\nMaking movie with ffmpeg...\n"

ffmpeg -framerate 25 -i "output_%d.png" -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" -vcodec libx264  geometry.mp4

#ffmpeg -pattern_type glob -i "${args[0]}_*.png" -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" -vcodec libx264 -crf 25 "${args[0]}.mp4"

#echo -e "\nRemoving .png...\n"

rm *.png

